### ISSUE TITLE
À quoi sert cette condition ? 😏

### ISSUE THREAD

**Issue by gaeVG** [DakoooM/iBanque#1]
https://github.com/DakoooM/iBanque/blob/581d4328419a5939f94033dee08b9aa2906c0488/client.lua#L13

**Comment by DakoooM** [comment]
elle sert a définir si le callback esx va call la table dans le SQL ou l'argent en banque du joueur

**Comment by gaeVG** [comment]
Sûr ? Parce que quand tu regardes côté serveur, à aucun moment ton callback ne renvoit un string 🤷‍♂️ ça marche vraiment ?
https://github.com/DakoooM/iBanque/blob/581d4328419a5939f94033dee08b9aa2906c0488/server.lua#L62

https://github.com/DakoooM/iBanque/blob/581d4328419a5939f94033dee08b9aa2906c0488/server.lua#L65

**Comment by DakoooM** [comment]
oui ca marche, ca callback l'élément que je lui donne selon la conditon qui est validée (PS : ca renvoi une table ou un nombre)

**Comment by gaeVG** [comment]
🤷‍♂️ si tu l'dis, visuellement ça passe pas mais je l'ai pas testé 🤭
